[package]
name = "advent2018"
version = "0.1.0"
authors = ["CJ Carey <perimosocordiae@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.0"
ndarray = "0.12.0"
petgraph = "0.4.0"
criterion-plot = "0.2.5"
