[package]
name = "advent2020"
version = "0.1.0"
authors = ["CJ Carey <perimosocordiae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4"
scan_fmt = "0.2"
itertools = "0.9"